import type { Generator, GeneratedFile, GenerationOptions } from "./generator.js";
import type { CollectionDefinition, FieldDefinition } from "@arche-cms/types";

function fieldToInputType(field: FieldDefinition): string {
  switch (field.type) {
    case "text":
      return "text";
    case "textarea":
      return "textarea";
    case "number":
      return "number";
    case "boolean":
      return "checkbox";
    case "date":
      return "date";
    case "datetime":
      return "datetime";
    case "email":
      return "email";
    case "password":
      return "password";
    case "url":
      return "url";
    case "json":
      return "json";
    case "richText":
      return "richText";
    case "markdown":
      return "markdown";
    case "code":
      return "code";
    case "color":
      return "color";
    case "media":
    case "upload":
      return "media";
    case "select":
      return "select";
    case "multiSelect":
      return "multiSelect";
    case "radio":
      return "radio";
    case "checkbox":
      return "checkbox";
    case "slug":
      return "slug";
    case "relation":
      return "relation";
    default:
      return "text";
  }
}

function generateAdminForm(collections: CollectionDefinition[]): string {
  const lines: string[] = [
    "// Auto-generated by @arche-cms/generators — do not edit manually",
    `import type { FieldDefinition } from "@arche-cms/types";`,
    "",
    "export interface FormConfig {",
    "  collection: string;",
    "  fields: Array<{",
    "    name: string;",
    "    type: string;",
    "    input: string;",
    "    label?: string;",
    "    required: boolean;",
    "  }>;",
    "}",
    "",
  ];

  for (const col of collections) {
    lines.push(`export const ${col.slug}FormConfig: FormConfig = {`);
    lines.push(`  collection: "${col.slug}",`);
    lines.push(`  fields: [`);

    for (const f of col.fields) {
      const inputType = fieldToInputType(f);
      const required = f.validation?.required ?? false;
      lines.push(
        `    { name: "${f.name}", type: "${f.type}", input: "${inputType}", label: ${f.label ? JSON.stringify(f.label) : undefined}, required: ${required} },`,
      );
    }

    lines.push(`  ],`);
    lines.push(`};`);
    lines.push(``);
  }

  return lines.join("\n");
}

export const adminFormGenerator: Generator = {
  name: "admin-forms",
  description: "Generates admin form configurations from collection definitions",
  async generate(options: GenerationOptions): Promise<GeneratedFile[]> {
    if (!options.collections || options.collections.length === 0) return [];

    return [
      {
        path: "admin-forms/index.ts",
        content: generateAdminForm(options.collections),
      },
    ];
  },
};
