import type { Generator, GeneratedFile, GenerationOptions } from "./generator.js";
import type { CollectionDefinition } from "@arche-cms/types";

function jsValue(val: unknown): string {
  if (val === undefined) return "undefined";
  if (val === null) return "null";
  if (typeof val === "string") return JSON.stringify(val);
  if (typeof val === "number" || typeof val === "boolean") return String(val);
  if (Array.isArray(val)) return `[${val.map(jsValue).join(", ")}]`;
  if (typeof val === "object") {
    const entries = Object.entries(val as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    return `{ ${entries.map(([k, v]) => `${JSON.stringify(k)}: ${jsValue(v)}`).join(", ")} }`;
  }
  return String(val);
}

function generateRoutesFile(collections: CollectionDefinition[]): string {
  const lines: string[] = [
    "// Auto-generated by @arche-cms/generators — do not edit manually",
    `import type { FastifyInstance } from "fastify";`,
    `import type { DatabaseAdapter } from "@arche-cms/database";`,
    `import { createCollectionRouter, createGlobalRouter } from "@arche-cms/rest-api";`,
    "",
    `export async function registerGeneratedRoutes(`,
    `  app: FastifyInstance,`,
    `  adapter: DatabaseAdapter,`,
    `): Promise<void> {`,
  ];

  for (const col of collections) {
    const varName = col.slug.replace(/[-.]/g, "_");
    const def = `createCollectionRouter(${jsValue(col)}, adapter)`;
    lines.push(`  const ${varName} = ${def};`);
    lines.push(`  for (const route of ${varName}.routes) {`);
    lines.push(`    app.route(route);`);
    lines.push("  }");
    lines.push("");
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export const apiRoutesGenerator: Generator = {
  name: "api-routes",
  description: "Generates API route registration files",
  async generate(options: GenerationOptions): Promise<GeneratedFile[]> {
    if (!options.collections || options.collections.length === 0) return [];

    return [
      {
        path: "routes/index.ts",
        content: generateRoutesFile(options.collections),
      },
    ];
  },
};
