import type { CollectionDefinition, FieldDefinition } from "@arche-cms/types";

import type { Generator, GeneratedFile, GenerationOptions } from "./generator.js";

function toPascal(s: string): string {
  return s.replace(/(^\w|[-_]\w)/g, (c) => c.replace(/[-_]/g, "").toUpperCase());
}

const fieldTypeToGraphQL: Record<string, string> = {
  array: "[JSON!]",
  boolean: "Boolean",
  checkbox: "Boolean",
  code: "String",
  color: "String",
  date: "String",
  datetime: "String",
  email: "String",
  group: "JSON",
  json: "JSON",
  markdown: "String",
  media: "String",
  multiSelect: "[String]",
  number: "Float",
  object: "JSON",
  password: "String",
  radio: "String",
  repeater: "[JSON!]",
  richText: "JSON",
  select: "String",
  slug: "String",
  tabs: "JSON",
  text: "String",
  textarea: "String",
  upload: "String",
  url: "String",
};

function fieldToGraphQLType(field: FieldDefinition): string {
  const mapped = fieldTypeToGraphQL[field.type];
  if (mapped) return mapped;
  if (field.type === "relation") return toPascal(field.to);
  if (field.type === "component") return toPascal(field.component ?? "");
  if (field.type === "dynamicZone") return field.components.map((c) => toPascal(c)).join(" | ");
  return "String";
}

function generateGraphQLFiles(collections: CollectionDefinition[]): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  const typeDefs: string[] = [
    `# Auto-generated by @arche-cms/generators — do not edit manually`,
    ``,
  ];

  for (const col of collections) {
    const name = toPascal(col.slug);
    typeDefs.push(`type ${name} {`);
    typeDefs.push(`  id: ID!`);
    typeDefs.push(`  createdAt: String`);
    typeDefs.push(`  updatedAt: String`);
    for (const f of col.fields) {
      const t = fieldToGraphQLType(f);
      const required = f.validation?.required ? "!" : "";
      typeDefs.push(`  ${f.name}: ${t}${required}`);
    }
    typeDefs.push(`}`);
    typeDefs.push(``);

    typeDefs.push(`input ${name}CreateInput {`);
    for (const f of col.fields) {
      if (f.type === "relation") continue;
      typeDefs.push(`  ${f.name}: ${fieldToGraphQLType(f)}`);
    }
    typeDefs.push(`}`);
    typeDefs.push(``);

    typeDefs.push(`input ${name}UpdateInput {`);
    for (const f of col.fields) {
      if (f.type === "relation") continue;
      typeDefs.push(`  ${f.name}: ${fieldToGraphQLType(f)}`);
    }
    typeDefs.push(`}`);
    typeDefs.push(``);
  }

  typeDefs.push(`type Query {`);
  for (const col of collections) {
    const name = toPascal(col.slug);
    typeDefs.push(`  ${col.slug}(id: ID!): ${name}`);
    typeDefs.push(`  all${name}(limit: Int, offset: Int, sort: String): [${name}]`);
  }
  typeDefs.push(`}`);
  typeDefs.push(``);

  typeDefs.push(`type Mutation {`);
  for (const col of collections) {
    const name = toPascal(col.slug);
    typeDefs.push(`  create${name}(input: ${name}CreateInput!): ${name}`);
    typeDefs.push(`  update${name}(id: ID!, input: ${name}UpdateInput!): ${name}`);
    typeDefs.push(`  delete${name}(id: ID!): Boolean`);
  }
  typeDefs.push(`}`);

  const resolversCode: string[] = [
    `// Auto-generated by @arche-cms/generators — do not edit manually`,
    `import type { DatabaseAdapter } from "@arche-cms/database";`,
    ``,
    `export function createResolvers(adapter: DatabaseAdapter): Record<string, unknown> {`,
    `  return {`,
    `    Query: {`,
  ];

  for (const col of collections) {
    const name = toPascal(col.slug);
    resolversCode.push(
      `      ${col.slug}: async (_: unknown, args: { id: string }) => adapter.findOne({ collection: "${col.slug}", id: args.id }),`,
    );
    resolversCode.push(
      `      all${name}: async (_: unknown, args: { limit?: number; offset?: number }) => adapter.findMany({ collection: "${col.slug}", limit: args.limit, offset: args.offset }),`,
    );
  }

  resolversCode.push(`    },`);
  resolversCode.push(`    Mutation: {`);

  for (const col of collections) {
    const name = toPascal(col.slug);
    resolversCode.push(
      `      create${name}: async (_: unknown, args: { input: Record<string, unknown> }) => adapter.create({ collection: "${col.slug}", data: args.input }),`,
    );
    resolversCode.push(
      `      update${name}: async (_: unknown, args: { id: string; input: Record<string, unknown> }) => adapter.update({ collection: "${col.slug}", id: args.id, data: args.input }),`,
    );
    resolversCode.push(
      `      delete${name}: async (_: unknown, args: { id: string }) => { await adapter.delete({ collection: "${col.slug}", id: args.id }); return true; },`,
    );
  }

  resolversCode.push(`    },`);
  resolversCode.push(`  };`);
  resolversCode.push(`}`);
  resolversCode.push(``);

  files.push({ content: typeDefs.join("\n"), path: "graphql/schema.graphql" });
  files.push({ content: resolversCode.join("\n"), path: "graphql/resolvers.ts" });

  return files;
}

export const graphqlGenerator: Generator = {
  description: "Generates GraphQL schema and resolvers from collection definitions",
  async generate(options: GenerationOptions): Promise<GeneratedFile[]> {
    if (!options.collections || options.collections.length === 0) return [];

    return generateGraphQLFiles(options.collections);
  },
  name: "graphql",
};
