import type { CollectionDefinition } from "@arche-cms/types";

import type { Generator, GeneratedFile, GenerationOptions } from "./generator.js";

function fieldToColumnType(type: string): string {
  switch (type) {
    case "text":
      return "TEXT";
    case "textarea":
      return "TEXT";
    case "number":
      return "REAL";
    case "boolean":
      return "INTEGER";
    case "date":
      return "TEXT";
    case "datetime":
      return "TEXT";
    case "email":
      return "TEXT";
    case "password":
      return "TEXT";
    case "url":
      return "TEXT";
    case "json":
      return "TEXT";
    case "richText":
      return "TEXT";
    case "markdown":
      return "TEXT";
    case "code":
      return "TEXT";
    case "color":
      return "TEXT";
    case "media":
      return "TEXT";
    case "upload":
      return "TEXT";
    case "select":
      return "TEXT";
    case "multiSelect":
      return "TEXT";
    case "radio":
      return "TEXT";
    case "checkbox":
      return "INTEGER";
    case "slug":
      return "TEXT";
    case "relation":
      return "TEXT";
    default:
      return "TEXT";
  }
}

function generateMigrationFile(collections: CollectionDefinition[]): string {
  const lines: string[] = [
    "// Auto-generated by @arche-cms/generators — do not edit manually",
    `import type { Migration } from "@arche-cms/database";`,
    "",
    `const migration: Migration = {`,
    `  name: "${new Date().toISOString().split("T")[0]}_initial_schema",`,
    `  up: async (adapter) => {`,
  ];

  for (const col of collections) {
    const tableName = `__cms_${col.slug}`;
    lines.push(`    await adapter.raw(\`CREATE TABLE IF NOT EXISTS ${tableName} (`);
    lines.push(`      id TEXT PRIMARY KEY,`);
    lines.push(`      created_at TEXT DEFAULT (datetime('now')),`);
    lines.push(`      updated_at TEXT DEFAULT (datetime('now'))`);
    for (const f of col.fields) {
      const colType = fieldToColumnType(f.type);
      lines.push(`      ,${f.name} ${colType}`);
    }
    lines.push(`    )\`);`);
    lines.push("");
  }

  lines.push(`  },`);
  lines.push(`  down: async (adapter) => {`);

  for (const col of collections) {
    lines.push(`    await adapter.executeSql(\`DROP TABLE IF EXISTS __cms_${col.slug}\`);`);
  }

  lines.push(`  },`);
  lines.push(`};`);
  lines.push("");
  lines.push("export default migration;");
  lines.push("");

  return lines.join("\n");
}

export const migrationGenerator: Generator = {
  description: "Generates database migration files from collection definitions",
  async generate(options: GenerationOptions): Promise<GeneratedFile[]> {
    if (!options.collections || options.collections.length === 0) return [];

    return [
      {
        content: generateMigrationFile(options.collections),
        path: `migrations/${new Date().toISOString().split("T")[0]}_initial_schema.ts`,
      },
    ];
  },
  name: "migrations",
};
