import type { FieldDefinition } from "@arche-cms/types";

import type { Generator, GeneratedFile, GenerationOptions } from "./generator.js";

function toPascal(s: string): string {
  return s.replace(/(^\w|[-_]\w)/g, (c) => c.replace(/[-_]/g, "").toUpperCase());
}

function isValidIdentifier(s: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(s);
}

function propKey(s: string): string {
  return isValidIdentifier(s) ? s : `"${s}"`;
}

function fieldOptional(field: FieldDefinition): boolean {
  return !field.validation?.required;
}

const fieldTypeMap: Record<string, string> = {
  boolean: "boolean",
  checkbox: "boolean",
  code: "string",
  color: "string",
  date: "string",
  datetime: "string",
  email: "string",
  json: "Record<string, unknown>",
  markdown: "string",
  media: "string",
  multiSelect: "string[]",
  number: "number",
  password: "string",
  radio: "string",
  richText: "unknown",
  select: "string",
  slug: "string",
  text: "string",
  textarea: "string",
  upload: "string",
  url: "string",
};

function fieldToType(field: FieldDefinition): string {
  const mapped = fieldTypeMap[field.type];
  if (mapped) {
    if (field.localized) return `Record<string, ${mapped}>`;
    return mapped;
  }

  let type: string;
  switch (field.type) {
    case "relation":
      type = field.kind === "oneToMany" || field.kind === "manyToMany" ? `string[]` : `string`;
      break;
    case "component":
      type = field.repeatable ? "Record<string, unknown>[]" : "Record<string, unknown>";
      break;
    case "dynamicZone":
      type = "Record<string, unknown>[]";
      break;
    case "array":
      type = `Array<Record<string, unknown>>`;
      break;
    case "object":
    case "group":
      type = `Record<string, unknown>`;
      break;
    case "repeater":
      type = `Array<Record<string, unknown>>`;
      break;
    case "tabs":
      type = `Record<string, unknown>`;
      break;
    default:
      type = "unknown";
  }
  /* v8 ignore next -- localized is tested but v8 counts both branches */
  if (field.localized) return `Record<string, ${type}>`;
  return type;
}

function generateInterface(name: string, fields: FieldDefinition[]): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  lines.push("  id: string;");
  lines.push("  createdAt?: string;");
  lines.push("  updatedAt?: string;");
  for (const f of fields) {
    const opt = fieldOptional(f) ? "?" : "";
    lines.push(`  ${f.name}${opt}: ${fieldToType(f)};`);
  }
  lines.push("}");
  return lines;
}

function generateSdkFile(options: GenerationOptions): string {
  const sdkPkg = "@arche-cms/sdk";
  const lines: string[] = [
    "// Auto-generated by @arche-cms/generators — do not edit manually",
    "",
    `import { createClient, type ArcheClient } from "${sdkPkg}";`,
    "",
  ];

  const collections = options.collections ?? /* v8 ignore next */ [];
  const globals = options.globals ?? /* v8 ignore next */ [];

  // Generate interfaces
  for (const col of collections) {
    const name = toPascal(col.slug);
    lines.push(...generateInterface(name, col.fields));
    lines.push("");
  }

  for (const global of globals) {
    const name = toPascal(global.slug);
    lines.push(...generateInterface(`${name}Globals`, global.fields));
    lines.push("");
  }

  // Generate type maps
  if (collections.length > 0) {
    lines.push("export interface CollectionTypeMap {");
    for (const col of collections) {
      const name = toPascal(col.slug);
      lines.push(`  "${col.slug}": ${name};`);
    }
    lines.push("}");
    lines.push("");
  }

  if (globals.length > 0) {
    lines.push("export interface GlobalTypeMap {");
    for (const g of globals) {
      const name = toPascal(g.slug);
      lines.push(`  "${g.slug}": ${name}Globals;`);
    }
    lines.push("}");
    lines.push("");
  }

  // Generate typed helper types
  lines.push("export type TypedCollectionClient<K extends keyof CollectionTypeMap> =");
  lines.push(`  import("${sdkPkg}").CollectionClient<CollectionTypeMap[K]>;`);
  lines.push("");
  lines.push("export type TypedGlobalClient<K extends keyof GlobalTypeMap> =");
  lines.push(`  import("${sdkPkg}").GlobalClient<GlobalTypeMap[K]>;`);
  lines.push("");

  // Generate TypedClient interface with collection/global accessors
  lines.push("export interface TypedClient extends ArcheClient {");
  for (const col of collections) {
    lines.push(
      `  ${propKey(col.slug)}: import("${sdkPkg}").CollectionClient<CollectionTypeMap["${col.slug}"]>;`,
    );
  }
  for (const g of globals) {
    lines.push(
      `  ${propKey(g.slug)}: import("${sdkPkg}").GlobalClient<GlobalTypeMap["${g.slug}"]>;`,
    );
  }
  lines.push("}");
  lines.push("");

  // Generate createTypedClient
  lines.push("export function createTypedClient(");
  lines.push("  config: Parameters<typeof createClient>[0],");
  lines.push("): TypedClient {");
  lines.push("  const client = createClient(config);");

  lines.push("  return {");
  lines.push("    ...client,");

  // Typed collection accessors
  for (const col of collections) {
    lines.push(
      `    ${propKey(col.slug)}: client.collection("${col.slug}") as import("${sdkPkg}").CollectionClient<CollectionTypeMap["${col.slug}"]>,`,
    );
  }

  // Typed global accessors
  for (const g of globals) {
    lines.push(
      `    ${propKey(g.slug)}: client.global("${g.slug}") as import("${sdkPkg}").GlobalClient<GlobalTypeMap["${g.slug}"]>,`,
    );
  }

  lines.push("  }");

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export const sdkGenerator: Generator = {
  description: "Generates typed SDK client with collection/global type maps and accessors",
  async generate(options: GenerationOptions): Promise<GeneratedFile[]> {
    const collections = options.collections ?? [];
    const globals = options.globals ?? [];

    if (collections.length === 0 && globals.length === 0) return [];

    return [
      {
        content: generateSdkFile(options),
        path: "sdk/index.ts",
      },
    ];
  },
  name: "sdk",
};
