import type { CollectionDefinition, FieldDefinition } from "@arche-cms/types";

import type { Generator, GeneratedFile, GenerationOptions } from "./generator.js";

function toPascal(s: string): string {
  return s.replace(/(^\w|[-_]\w)/g, (c) => c.replace(/[-_]/g, "").toUpperCase());
}

function fieldToTsType(field: FieldDefinition): string {
  switch (field.type) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "Record<string, unknown>";
    case "richText":
      return "string";
    case "multiSelect":
      return "string[]";
    case "relation":
      return "string";
    case "date":
      return "string";
    case "datetime":
      return "string";
    case "array":
      return "Array<Record<string, unknown>>";
    case "object":
    case "group":
      return "Record<string, unknown>";
    case "repeater":
      return "Array<Record<string, unknown>>";
    case "tabs":
      return "Record<string, unknown>";
    case "component":
      return "Record<string, unknown>";
    case "dynamicZone":
      return "Array<Record<string, unknown>>";
    default:
      return "string";
  }
}

function generateSdkClass(collections: CollectionDefinition[]): string {
  const lines: string[] = [
    "// Auto-generated by @arche-cms/generators — do not edit manually",
    "",
    "export interface SdkConfig {",
    "  baseUrl: string;",
    "  token?: string;",
    "}",
    "",
    "export class ArcheCMSClient {",
    "  private baseUrl: string;",
    "  private token?: string;",
    "",
    "  constructor(config: SdkConfig) {",
    "    this.baseUrl = config.baseUrl.replace(/\\/+$/, '');",
    "    this.token = config.token;",
    "  }",
    "",
    "  private headers(): Record<string, string> {",
    "    const h: Record<string, string> = {",
    '      "Content-Type": "application/json",',
    "    };",
    "    if (this.token) h['Authorization'] = `Bearer ${this.token}`;",
    "    return h;",
    "  }",
    "",
    "  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {",
    "    const res = await fetch(`${this.baseUrl}${path}`, {",
    "      method,",
    "      headers: this.headers(),",
    "      body: body ? JSON.stringify(body) : undefined,",
    "    });",
    "    if (!res.ok) {",
    "      const err = await res.json().catch(() => ({ error: res.statusText }));",
    "      throw new Error(err.error ?? `HTTP ${res.status}`);",
    "    }",
    "    return res.json() as Promise<T>;",
    "  }",
    "",
  ];

  for (const col of collections) {
    const name = toPascal(col.slug);

    const typeProps = col.fields
      .map((f) => `    ${f.name}${f.validation?.required ? "" : "?"}: ${fieldToTsType(f)};`)
      .join("\n");

    lines.push(`  export interface ${name} {`);
    lines.push(`    id: string;`);
    lines.push(`    createdAt: string;`);
    lines.push(`    updatedAt: string;`);
    lines.push(typeProps);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  async get${name}(id: string): Promise<${name}> {`);
    lines.push(`    return this.request<${name}>("GET", \`/api/collections/${col.slug}/\${id}\`);`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(
      `  async list${name}(params?: { limit?: number; offset?: number }): Promise<${name}[]> {`,
    );
    const query = `params ? \`?limit=\${params.limit ?? 10}&offset=\${params.offset ?? 0}\` : ""`;
    lines.push(
      `    return this.request<${name}[]>("GET", \`/api/collections/${col.slug}\${${query}}\`);`,
    );
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  async create${name}(data: Partial<${name}>): Promise<${name}> {`);
    lines.push(`    return this.request<${name}>("POST", \`/api/collections/${col.slug}\`, data);`);
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  async update${name}(id: string, data: Partial<${name}>): Promise<${name}> {`);
    lines.push(
      `    return this.request<${name}>("PUT", \`/api/collections/${col.slug}/\${id}\`, data);`,
    );
    lines.push(`  }`);
    lines.push(``);

    lines.push(`  async delete${name}(id: string): Promise<void> {`);
    lines.push(`    return this.request<void>("DELETE", \`/api/collections/${col.slug}/\${id}\`);`);
    lines.push(`  }`);
    lines.push(``);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export const sdkGenerator: Generator = {
  description: "Generates TypeScript SDK client from collection definitions",
  async generate(options: GenerationOptions): Promise<GeneratedFile[]> {
    if (!options.collections || options.collections.length === 0) return [];

    return [
      {
        content: generateSdkClass(options.collections),
        path: "sdk/index.ts",
      },
    ];
  },
  name: "sdk",
};
