import type {
  CollectionDefinition,
  GlobalDefinition,
  ComponentDefinition,
  FieldDefinition,
} from "@arche-cms/types";

import { writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";

export interface TypeGenOptions {
  collections?: CollectionDefinition[] | undefined;
  globals?: GlobalDefinition[] | undefined;
  components?: ComponentDefinition[] | undefined;
  outputPath: string;
}

const fieldTypeMap: Record<string, string> = {
  boolean: "boolean",
  checkbox: "boolean",
  code: "string",
  color: "string",
  date: "string",
  datetime: "string",
  email: "string",
  json: "Record<string, unknown>",
  markdown: "string",
  media: "string",
  multiSelect: "string[]",
  number: "number",
  password: "string",
  radio: "string",
  richText: "unknown",
  select: "string",
  slug: "string",
  text: "string",
  textarea: "string",
  upload: "string",
  url: "string",
};

function fieldToType(field: FieldDefinition): string {
  const mapped = fieldTypeMap[field.type];
  if (mapped) {
    if (field.localized) return `Record<string, ${mapped}>`;
    return mapped;
  }

  let type: string;
  switch (field.type) {
    case "relation":
      type =
        field.kind === "oneToMany" || field.kind === "manyToMany"
          ? `${toPascal(field.to)}[]`
          : `${toPascal(field.to)} | string`;
      break;
    case "component":
      type = field.repeatable ? `${toPascal(field.component)}[]` : toPascal(field.component);
      break;
    case "dynamicZone":
      type = field.components.map((c) => toPascal(c)).join(" | ");
      break;
    case "array":
      type = `Array<{${field.fields.map((f) => `${f.name}: ${fieldToType(f)}`).join("; ")}}>`;
      break;
    case "object":
    case "group":
      type = `{${field.fields.map((f) => `${f.name}: ${fieldToType(f)}`).join("; ")}}`;
      break;
    case "repeater":
      type = `Array<{${field.fields.map((f) => `${f.name}: ${fieldToType(f)}`).join("; ")}}>`;
      break;
    case "tabs":
      type = `{${field.tabs.flatMap((t) => t.fields.map((f) => `${f.name}: ${fieldToType(f)}`)).join("; ")}}`;
      break;
    default:
      type = "unknown";
  }
  if (field.localized) return `Record<string, ${type}>`;
  return type;
}

function toPascal(s: string): string {
  return s.replace(/(^\w|[-_]\w)/g, (c) => c.replace(/[-_]/g, "").toUpperCase());
}

function fieldOptional(field: FieldDefinition): boolean {
  return !field.validation?.required;
}

function generateFields(fields: FieldDefinition[]): string[] {
  return fields.map((f) => `  ${f.name}${fieldOptional(f) ? "?" : ""}: ${fieldToType(f)};`);
}

export function generateTypes(options: TypeGenOptions): string {
  const lines: string[] = ["// Auto-generated by @arche-cms/generators — do not edit manually", ""];

  if (options.components) {
    for (const comp of options.components) {
      lines.push(`export interface ${toPascal(comp.slug)} {`);
      lines.push(...generateFields(comp.fields));
      lines.push("}");
      lines.push("");
    }
  }

  if (options.globals) {
    for (const global of options.globals) {
      lines.push(`export interface ${toPascal(global.slug)} {`);
      lines.push(...generateFields(global.fields));
      lines.push("}");
      lines.push("");
    }
  }

  if (options.collections) {
    for (const col of options.collections) {
      lines.push(`export interface ${toPascal(col.slug)} {`);
      lines.push("  id: string;");
      const ts = col.timestamps === false ? { createdAt: false, updatedAt: false } : (col.timestamps ?? { createdAt: true, updatedAt: true });
      if (ts.createdAt !== false) lines.push("  createdAt?: string;");
      if (ts.updatedAt !== false) lines.push("  updatedAt?: string;");
      lines.push(...generateFields(col.fields));
      lines.push("}");
      lines.push("");
    }
  }

  return lines.join("\n");
}

export async function generateTypesToFile(options: TypeGenOptions): Promise<void> {
  const content = generateTypes(options);
  const outPath = resolve(options.outputPath);
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, content, "utf-8");
}
